module.exports = {
    PROCESSED_TEXT_COMMAND: 1,
    PROCESSED_TEXT_PHONE: 2,
    PROCESSED_TEXT_ADDRESS: 0,
    PROCESSED_TEXT_TOP: 0,
    PROCESSED_TEXT_XNUMBER: 2,
    PROCESSED_TEXT_EVENTS: 0,  
    PROCESSED_TEXT_LATITUDE: 1, 
    PROCESSED_TEXT_LONGITUDE: 2  
};